# Generated by Django 4.2.30 on 2026-09-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcid', models.CharField(max_length=100, unique=True, verbose_name='TCID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='用例描述')),
                ('need_run', models.BooleanField(default=False, verbose_name='是否需要执行')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('last_result', models.CharField(blank=True, default='', max_length=50, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['tcid'],
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField(default=1, verbose_name='步骤序号')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='测试步骤描述')),
                ('keyword', models.CharField(blank=True, default='', max_length=100, verbose_name='关键字')),
                ('locate_type', models.CharField(blank=True, default='', max_length=50, verbose_name='定位方式')),
                ('locate_expr', models.CharField(blank=True, default='', max_length=500, verbose_name='定位表达式')),
                ('value', models.TextField(blank=True, default='', verbose_name='操作值')),
                ('need_run', models.BooleanField(default=True, verbose_name='是否需要执行')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cases.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '测试步骤',
                'verbose_name_plural': '测试步骤',
                'ordering': ['case', 'step_no'],
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(blank=True, default='', max_length=100, verbose_name='CaseId')),
                ('runmode', models.CharField(default='y', max_length=10, verbose_name='Runmode')),
                ('data_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Data_name')),
                ('summary', models.CharField(blank=True, default='', max_length=300, verbose_name='Summary')),
                ('input1', models.TextField(blank=True, default='', verbose_name='Input1')),
                ('input2', models.TextField(blank=True, default='', verbose_name='Input2')),
                ('input3', models.TextField(blank=True, default='', verbose_name='Input3')),
                ('input4', models.TextField(blank=True, default='', verbose_name='Input4')),
                ('input5', models.TextField(blank=True, default='', verbose_name='Input5')),
                ('input6', models.TextField(blank=True, default='', verbose_name='Input6')),
                ('input7', models.TextField(blank=True, default='', verbose_name='Input7')),
                ('input8', models.TextField(blank=True, default='', verbose_name='Input8')),
                ('verifiedcode_xy', models.CharField(blank=True, default='', max_length=100, verbose_name='verifiedcodeXY')),
                ('selector1', models.CharField(blank=True, default='', max_length=500, verbose_name='selector1')),
                ('selector2', models.CharField(blank=True, default='', max_length=500, verbose_name='selector2')),
                ('assert_type', models.TextField(blank=True, default='', verbose_name='Type')),
                ('expression', models.TextField(blank=True, default='', verbose_name='Expression')),
                ('expected_result', models.TextField(blank=True, default='', verbose_name='ExpectedResult')),
                ('cycle', models.IntegerField(default=1, verbose_name='Cycle')),
                ('errmsg', models.TextField(blank=True, default='', verbose_name='ErrMsg')),
                ('result', models.CharField(blank=True, default='', max_length=50, verbose_name='Result')),
                ('start_time', models.CharField(blank=True, default='', max_length=50, verbose_name='StartTime')),
                ('run_time', models.CharField(blank=True, default='', max_length=50, verbose_name='RunTime')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='cases.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'ordering': ['case', 'id'],
            },
        ),
    ]
