# Generated by Django 4.2.30 on 2026-09-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='selector3',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='selector3'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='selector4',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='selector4'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='selector5',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='selector5'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='selector6',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='selector6'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='selector7',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='selector7'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='selector8',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='selector8'),
        ),
    ]
