# Generated by Django 4.2.30 on 2026-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_testdata_selector3_testdata_selector4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='cycle',
            field=models.IntegerField(default=1, verbose_name='循环次数'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='last_duration',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='耗时'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='last_errmsg',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='last_start_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='开始时间'),
        ),
    ]
