# Generated by Django 4.2.30 on 2026-09-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_testcase_cycle_testcase_last_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teststep',
            options={'ordering': ['case', 'step_no', 'id'], 'verbose_name': '测试步骤', 'verbose_name_plural': '测试步骤'},
        ),
    ]
