# Generated by Django 4.2.30 on 2026-09-14 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0004_alter_teststep_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='StepSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('save', '保存步骤'), ('copy', '复制步骤前'), ('restore', '还原前'), ('import', '导入覆盖前')], default='save', max_length=20, verbose_name='变更原因')),
                ('step_count', models.IntegerField(default=0, verbose_name='步骤条数')),
                ('payload', models.JSONField(blank=True, default=list, verbose_name='步骤快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cases.testcase', verbose_name='所属用例')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '步骤快照',
                'verbose_name_plural': '步骤快照',
                'ordering': ['-created_at'],
            },
        ),
    ]
