# Generated by Django 4.2.30 on 2026-09-08 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '全部通过'), ('failed', '存在失败'), ('error', '执行异常')], default='pending', max_length=20, verbose_name='状态')),
                ('case_filter', models.CharField(blank=True, default='全部启用用例', max_length=500, verbose_name='执行范围')),
                ('total', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过')),
                ('failed', models.IntegerField(default=0, verbose_name='失败')),
                ('error', models.IntegerField(default=0, verbose_name='异常')),
                ('current_step', models.CharField(blank=True, default='', max_length=300, verbose_name='当前步骤')),
                ('log_tail', models.TextField(blank=True, default='', verbose_name='日志尾部')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='耗时(秒)')),
                ('report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='报告文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
