# Generated by Django 4.2.30 on 2026-09-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='已请求停止'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '全部通过'), ('failed', '存在失败'), ('error', '执行异常'), ('cancelled', '已停止')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
