# Generated by Django 4.2.30 on 2026-09-14 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runner', '0002_taskrun_cancel_requested_alter_taskrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='已发通知'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通知时间'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='notify_error',
            field=models.TextField(blank=True, default='', verbose_name='通知失败原因'),
        ),
        migrations.CreateModel(
            name='NotifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('notify_on', models.CharField(choices=[('fail', '仅执行失败/异常时'), ('always', '每次执行结束都发')], default='fail', max_length=10, verbose_name='发送时机')),
                ('smtp_host', models.CharField(blank=True, default='smtp.qq.com', max_length=200, verbose_name='SMTP 服务器')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='端口')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用 SSL（465 端口通常开）')),
                ('use_tls', models.BooleanField(default=False, verbose_name='使用 STARTTLS（587 端口通常开）')),
                ('username', models.CharField(blank=True, default='', max_length=200, verbose_name='登录账号')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密码 / 授权码')),
                ('sender', models.CharField(blank=True, default='', max_length=200, verbose_name='发件人邮箱')),
                ('receivers', models.TextField(blank=True, default='', verbose_name='收件人（多个用英文逗号分隔）')),
                ('attach_report', models.BooleanField(default=True, verbose_name='附上 HTML 报告附件')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '邮件通知配置',
                'verbose_name_plural': '邮件通知配置',
            },
        ),
    ]
