# Generated by Django 4.2.30 on 2026-09-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runner', '0003_taskrun_notified_taskrun_notified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('freq', models.CharField(choices=[('hourly', '每 N 小时'), ('daily', '每天'), ('weekly', '每周')], default='daily', max_length=10, verbose_name='频率')),
                ('interval_hours', models.IntegerField(default=2, verbose_name='间隔小时数')),
                ('hour', models.IntegerField(default=8, verbose_name='小时（0-23）')),
                ('minute', models.IntegerField(default=30, verbose_name='分钟（0-59）')),
                ('weekdays', models.CharField(blank=True, default='1', max_length=30, verbose_name='星期（1-7，逗号分隔）')),
                ('scope_type', models.CharField(choices=[('all', '全部启用用例'), ('tag', '按标签'), ('cases', '指定用例')], default='all', max_length=10, verbose_name='执行范围')),
                ('scope_value', models.CharField(blank=True, default='', max_length=500, verbose_name='范围参数（标签名或多个 TCID，逗号分隔）')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次触发')),
                ('last_status', models.CharField(blank=True, default='', max_length=100, verbose_name='上次结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('last_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_plans', to='runner.taskrun', verbose_name='上次执行记录')),
            ],
            options={
                'verbose_name': '定时计划',
                'verbose_name_plural': '定时计划',
                'ordering': ['name'],
            },
        ),
    ]
