# Generated by Django 4.2.30 on 2026-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_notify_sender_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='error_summary',
            field=models.TextField(blank=True, default='', verbose_name='异常摘要'),
        ),
    ]
